name: ETL diario a Supabase

on:
  push:
    paths:
      - 'etl_supabase.py'
      - 'requisitos.txt'
  schedule:
    # Ejecutar cada día a las 02:00 hora El Salvador (08:00 UTC)
    - cron: '0 8 * * *'

jobs:
  ejecutar-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requisitos.txt

      - name: Configurar token de Copernicus
        run: |
          mkdir -p ~/.cdsapirc
          echo "url: https://cds.climate.copernicus.eu/api" > ~/.cdsapirc
          echo "key: 123456:da593dcf-84ac-4790-a785-9aca76da8fee" >> ~/.cdsapirc

      - name: Ejecutar ETL
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: python etl_supabase.py


